alias vi='vim'
alias gds='echo " ------------------ USE FANCY STATUS INSTEAD -------------------"; git diff --staged'
alias ga='git add'
alias gs='echo " ------------------ USE FANCY STATUS INSTEAD -------------------"; git status'
alias gcm='git commit -m'
